name: CI

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
        
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
        
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run Pytest
              run: |
                pytest --exitfirst --disable-warnings --junitxml=report.xml
              continue-on-error: false  # Ensures failure if tests fail

            - name: Success Message
              if: success()
              run: echo "All tests passed! CI is successful."

            - name: Failure Message
              if: failure()
              run: echo "Tests failed! Please check the logs and fix errors."
          